name: Build macOS

permissions:
  contents: read
  actions: write

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/**'
      - 'Src/**'
      - 'version.txt'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12.10'
          architecture: 'arm64'
          cache: 'pip'

      - name: Get Shortened Commit SHA
        id: shorten_commit_sha
        uses: iendeavor/shorten-commit-sha@v2.0.4
        with:
          length: 7

      - name: Create virtual environment
        run: python3 -m venv .venv

      - name: Activate virtual environment
        run: source .venv/bin/activate

      - name: Install dependencies
        run: pip install --upgrade -r requirements.txt

      - name: Build with PyInstaller
        run: |
          pyinstaller --noconfirm --onefile --console --name "Workshop Decompressor" --strip --clean --optimize "2" --add-data "Src/extract_addons.py:." --add-data "Src/extract_archives.py:." --add-data "Src/utils.py:."  "Src/cli.py"

      - name: Move Bin Folder and Remove Gmad And 7-zip from Windows/Linux
        run: |
          cp -r Src/Bin dist/
          rm -r dist/Bin/Windows/fastgmad.exe
          rm -f dist/Bin/Windows/7z.exe
          rm -f dist/Bin/Linux/fastgmad
          rm -f dist/Bin/Linux/7z

      - name: Upload artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: VAE-${{ steps.shorten_commit_sha.outputs.shortened_commit_sha }}-macOS-ARM64
          path: dist
          compression-level: 9
