name: Build Windows

permissions:
  contents: read
  actions: write

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/**'
      - 'Src/**'
      - 'version.txt'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12.10'
          architecture: 'x64'
          cache: 'pip'

      - name: Get Shortened Commit SHA
        id: shorten_commit_sha
        uses: iendeavor/shorten-commit-sha@v2.0.5
        with:
          length: 7

      - name: Create virtual environment
        run: py -m venv .venv

      - name: Activate virtual environment
        run: .venv\Scripts\activate

      - name: Install dependencies
        run: pip install --upgrade -r requirements.txt

      - name: Build with PyInstaller
        run: |
          pyinstaller --noconfirm --onefile --console --icon "Src/Icon/WorkshopDecompressor.ico" --name "Workshop Decompressor" --clean --optimize "2" --version-file "version.txt" --add-data "Src/extract_addons.py;." --add-data "Src/extract_archives.py;." --add-data "Src/utils.py;."  "Src/cli.py"

      - name: Move Bin Folder and Remove Gmad And 7-zip from Linux/macOS
        run: |
          Copy-Item -Path "Src/Bin" -Destination "dist" -Recurse -Force
          Remove-Item -Path 'dist/Bin/Linux/fastgmad' -Force
          Remove-Item -Path 'dist/Bin/Darwin/fastgmad' -Force
          Remove-Item -Path 'dist/Bin/Linux/7z' -Force
          Remove-Item -Path 'dist/Bin/Darwin/7z' -Force

      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: WorkshopDecompressor-${{ steps.shorten_commit_sha.outputs.shortened_commit_sha }}-Windows-x64
          path: dist
          compression-level: 9
